### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by saulotarsobc** [saulotarsobc/jw-sing-language-merge#6]
```sh
>> Copiando dados da base-1 para a nova base
>> Copiando dados da base-2 para a nova base
Traceback (most recent call last):
  File "C:\Users\saulo\OneDrive\Documentos\Github\libras\jw-sing-language-merge\py\src\main.py", line 843, in <module>
    getDataFromDb2()
  File "C:\Users\saulo\OneDrive\Documentos\Github\libras\jw-sing-language-merge\py\src\main.py", line 746, in getDataFromDb2
    cur3.execute("INSERT INTO PlaylistItem VALUES(?,?,?,?,?,?,?)", (nextId, r[1], r[2], r[3], r[4], r[5], r[6]))
sqlite3
```

**Comment by saulotarsobc** [comment]
Bug fixed

**Comment by saulotarsobc** [comment]
Bug fixed
