### ISSUE TITLE
Bug in Location table

### ISSUE THREAD

**Issue by saulotarsobc** [saulotarsobc/jw-sing-language-merge#7]
```sh
>> Copiando dados da base-1 para a nova base
>> Copiando dados da base-2 para a nova base
Traceback (most recent call last):
  File "C:\Users\saulo\OneDrive\Documentos\Github\libras\jw-sing-language-merge\py\src\main.py", line 849, in <module>
    getDataFromDb2()
  File "C:\Users\saulo\OneDrive\Documentos\Github\libras\jw-sing-language-merge\py\src\main.py", line 695, in getDataFromDb2
    cur3.execute("INSERT INTO Location VALUES(?,?,?,?,?,?,?,?,?,?)", (nextId, r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9]))
sqlite3.IntegrityError: UNIQUE constraint failed: Location.BookNumber, Location.ChapterNumber, Location.KeySymbol, Location.MepsLanguage, Location.Type
```

**Comment by saulotarsobc** [comment]
> The error you are experiencing indicates that a UNIQUE constraint violation occurred when trying to insert data into the Location table. It appears that the values you are trying to insert already exist in the table, and because you have a uniqueness constraint on certain columns, the insertion is failing.

> To resolve this, I have to check if the values you are trying to insert already exist in the Location table before performing the insertion. If they already exist, you can choose to update the existing record or choose an action that suits your use case


🤯

**Comment by saulotarsobc** [comment]
Fixed

**Comment by saulotarsobc** [comment]
## Fixed

```py
# Location
data = cur2.execute("SELECT * FROM Location").fetchall()
nextId = cur3.execute("SELECT MAX(LocationId) FROM Location").fetchone()[0]

for r in data:
    nextId += 1
    existing_data = cur3.execute("SELECT * FROM Location WHERE BookNumber = ? AND ChapterNumber = ? AND KeySymbol = ? AND MepsLanguage = ? AND Type = ?", (r[1], r[2], r[6], r[7], r[8])).fetchone()
    if existing_data is None:
        mapId['Location'][r[0]] = nextId
        cur3.execute("INSERT INTO Location VALUES(?,?,?,?,?,?,?,?,?,?)", (nextId, r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9]))
    else:
        print(">> ⚠️ Mapenado IDs para a tabela Location")
        mapId['Location'][r[0]] = existing_data[0]
```
