### ISSUE TITLE
UNIQUE constraint failed: Location.KeySymbol, Location.IssueTagNumber, Location.MepsLanguage, Location.DocumentId, Location.Track, Location.Type

### ISSUE THREAD

**Issue by saulotarsobc** [saulotarsobc/jw-sing-language-merge#8]
```py
Traceback (most recent call last):
  File "C:\Users\saulo\OneDrive\Documentos\Github\libras\jw-sing-language-merge\py\src\main.py", line 932, in <module>
    getDataFromDb2()
  File "C:\Users\saulo\OneDrive\Documentos\Github\libras\jw-sing-language-merge\py\src\main.py", line 771, in getDataFromDb2
    cur3.execute("INSERT INTO Location VALUES(?,?,?,?,?,?,?,?,?,?)", (nextId, r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9]))
sqlite3.IntegrityError: UNIQUE constraint failed: Location.KeySymbol, Location.IssueTagNumber, Location.MepsLanguage, Location.DocumentId, Location.Track, Location.Type 
```

> The error sqlite3.IntegrityError: UNIQUE constraint failed: Location.KeySymbol, Location.IssueTagNumber, Location.MepsLanguage, Location.DocumentId, Location.Track, Location.Type indicates that there has been a violation of the unique key constraint on the Location table. This means that an insertion is being attempted that violates the uniqueness condition defined for the mentioned columns.

**Comment by saulotarsobc** [comment]
# Fixed

```py
# IndependentMedia
data = cur2.execute("SELECT * FROM IndependentMedia").fetchall()
nextId = cur3.execute("SELECT MAX(IndependentMediaId) FROM IndependentMedia").fetchone()[0]
for r in data:
    existing_data = cur3.execute("SELECT IndependentMediaId FROM IndependentMedia WHERE FilePath = ?", (r[2],)).fetchone()
    if existing_data:
        existing_id = existing_data[0]
        mapId['IndependentMedia'][r[0]] = existing_id
    else:
        nextId += 1
        cur3.execute("INSERT INTO IndependentMedia VALUES(?,?,?,?,?)", (nextId, r[1], r[2], r[3], r[4]))
        mapId['IndependentMedia'][r[0]] = nextId
```

**Comment by saulotarsobc** [comment]
# Fixed

```py
# Location
data = cur2.execute("SELECT * FROM Location").fetchall()
nextId = cur3.execute("SELECT MAX(LocationId) FROM Location").fetchone()[0]
for r in data:
    nextId += 1
    existing_data = cur3.execute("SELECT * FROM Location WHERE KeySymbol = ? OR IssueTagNumber = ? OR MepsLanguage = ? OR DocumentId = ? OR Track = ? OR Type = ?", ( r[6], r[5], r[7], r[3], r[4], r[8])).fetchone()
    if existing_data is None:
        mapId['Location'][r[0]] = nextId
        cur3.execute("INSERT INTO Location VALUES(?,?,?,?,?,?,?,?,?,?)", (nextId, r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9]))
    else:
        print(">> ⚠️ Mapenado IDs para a tabela Location")
        mapId['Location'][r[0]] = existing_data[0]
```

**Comment by saulotarsobc** [comment]
# Fixed

```py
# Location
data = cur2.execute("SELECT * FROM Location").fetchall()
nextId = cur3.execute("SELECT MAX(LocationId) FROM Location").fetchone()[0]
for r in data:
    nextId += 1
    existing_data = cur3.execute("SELECT * FROM Location WHERE KeySymbol = ? OR IssueTagNumber = ? OR MepsLanguage = ? OR DocumentId = ? OR Track = ? OR Type = ?", ( r[6], r[5], r[7], r[3], r[4], r[8])).fetchone()
    if existing_data is None:
        mapId['Location'][r[0]] = nextId
        cur3.execute("INSERT INTO Location VALUES(?,?,?,?,?,?,?,?,?,?)", (nextId, r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9]))
    else:
        print(">> ⚠️ Mapenado IDs para a tabela Location")
        mapId['Location'][r[0]] = existing_data[0]
```
